### PR TITLE
1.4.21

### LINKED ISSUE #21: Volumes are sorted in reverse after update to new 1.4.20
### Source information

1.4.20

### Source language

English

### Steps to reproduce

Connect to Kavita, view any title with both volumes and chapters.  Volumes are shown in the reverse order as chapters.  Chapters are show in the correct viewing order.  Assuming 3 volumes and 3 chapters, the listing ordert is presented as:
- Volume 3
- Volume 2
- Volume 1
- Chapter 1
- Chapter 2
- Chapter 3

Advancing from Chapter 1 will take you to Chapter 2.  Advancing from Volume 2 will take you to Volume 1.  And from Volume 1 will advance to Chapter 1.

### Expected behavior

Expected behavior would be a proper listing of:
- Volume 1
- Volume 2
- Volume 3
- Chapter 1
- Chapter 2
- Chapter 3

Also advancing from Volume 1 should take you to Volume 2, and from Volume 3 take you to Chapter 1 since it is that last volume. 

### Actual behavior

Volumes are shown in the reverse order as chapters.  Chapters are show in the correct viewing order.  Assuming 3 volumes and 3 chapters, the listing ordert is presented as:
- Volume 3
- Volume 2
- Volume 1
- Chapter 1
- Chapter 2
- Chapter 3

Advancing from Chapter 1 will take you to Chapter 2.  Advancing from Volume 2 will take you to Volume 1.  And from Volume 1 will advance to Chapter 1.

### Tachiyomi version

Mihon 0.18.0-7299 (r7299)

### Android version

Android 16

### Other details

Not sure if the troubleshooting guide still applies.  This plugin may also be more used with Mihon now?  And base version of that is 0.18.x

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### LINKED ISSUE #22: library filter causes 500 error
### Source information

tachi

### Source language

en

### Steps to reproduce

1. Access kavita extension
2. go to filters
3. activate library filter

### Expected behavior

Only items in that library appear

### Actual behavior

500 error appears

### Tachiyomi version

0.18.0

### Android version

16

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### LINKED ISSUE #24: Incorrect Volume/Chapter number parsing for "Zom 100" in Mihon
### Source information

Kavita 1.4.20 (latest)

### Source language

-

### Steps to reproduce

1. have this series in the volume format in kavita: https://myanimelist.net/manga/122392
2. add it to mihon using the extension

### Expected behavior

It should display actual volume numbers as it does on Kavita itself

Image

### Actual behavior

It displays all volumes as Chapter 100.

Image

### Tachiyomi version

Mihon 0.18.0

### Android version

Android 12

### Other details

Filename: `Zom 100 - Bucket List of the Dead v01 (2021) (Digital) (1r0n) (f2).cbz`

This does not happen when the same file is added as Local Source to mihon.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by dear-clouds**
This PR contains:
- Enhance logic for covers + add Comic Support
- Refactor chapters list parsing (fixes #21)
- Fixes Library filter (fixes #22)
- Update issue templates
- Fixes ChapterList parsing issue (fixes #24)
- Fixes Regular chapters treated as volumes
- Fixes Broken Language & Collection Filters
- Fixes Specials sometimes showing as blank
- Adds customization for Webtoons
- Adds support for range chapters/volumes
- Optimization/Upgrade from the old code

### CODE REVIEW

File: src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt [hunk 1]
```diff
@@ -1009,64 +1012,69 @@ class Kavita(private val suffix: String = "") : ConfigurableSource, UnmeteredSou
...
+                        GET("$apiUrl/Series/volumes?seriesId=$seriesId", headersBuilder().build()),
+                    ).execute().parseAs<List<VolumeDto>>()
+
+                    val libraryType = getLibraryType(seriesId)
+                    val isComicLibrary = libraryType == LibraryTypeEnum.Comic || libraryType == LibraryTypeEnum.ComicVine
+
+                    val coverCandidates = mutableListOf<Triple<String, Boolean, Float>>()
+
+                    for (volume in volumes) {
+                        if (isComicLibrary && volume.number == -100000) {
```
Comment (majora2007) [inline src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt:1027]: Put the encoding number into a variable so it's not just a magic number.

File: src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt [hunk 2]
```diff
@@ -1009,64 +1012,69 @@ class Kavita(private val suffix: String = "") : ConfigurableSource, UnmeteredSou
...
+                            // Issue: use chapter covers
+                            for (chapter in volume.chapters) {
+                                if (!chapter.coverImage.isNullOrBlank()) {
```
Comment (majora2007) [inline src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt:1030]: Use inversion of control. Flip the if statement so you can continue and reduce nesting. 

```

if (chapter.coverImage.isNullOrBlank()) continue;

...

```

File: src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/KavitaHelper.kt [hunk 3]
```diff
@@ -153,20 +120,24 @@ class KavitaHelper {
...
+                    chapter.number.toFloatOrNull() ?: 0f
+
+                // For volumes in mixed content, place them below chapter 0
+                else -> {
+                    val volumeNum = try {
+                        volume.number.toString().toFloatOrNull() ?: 0f
+                    } catch (e: NumberFormatException) {
+                        0f
+                    }
+                    -volumeNum - 100000f
```
Comment (majora2007) [inline src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/KavitaHelper.kt:139]: Another case of a magic number

**Review by majora2007 — CHANGES_REQUESTED** [review]

File: src/all/kavita/assets/i18n/messages_en.properties [hunk 4]
```diff
@@ -8,7 +8,7 @@ pref_group_tags_summary_on=Will prefix tags with their type
 pref_group_tags_summary_off=List all tags together
 pref_last_volume_cover_title=Keep cover updated
 pref_last_volume_cover_summary_off=Keep current cover
-pref_last_volume_cover_summary_on=Use the last volume cover when updating
+pref_last_volume_cover_summary_on=Update cover to current Volume/Issue
```
[the remark this answers is not in the document]
Comment (dear-clouds) [reply src/all/kavita/assets/i18n/messages_en.properties:11]: No we can't never modify Kavita from Mihon, it just update the cover in Mihon

**Review by majora2007 — APPROVED** [review]

**Comment by majora2007** [comment]
Can we post an apk to the mihon channel and give a chance for some shakeout first?

**Comment by dear-clouds** [comment]
Sure, I will post it.

Fyi, I tested the reported issues with the same titles as well just in case, and extensions update almost instantly in Mihon so they're quick fixes.
All these issues were related to the way I differentiate types now, but I still need to make the Mihon PR when I have time to go with it. It only causes tracking issues for now, as before my overhaul.

File: src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt [hunk 5]
```diff
@@ -401,8 +306,17 @@ class Kavita(private val suffix: String = "") : ConfigurableSource, UnmeteredSou
...
             statements = mutableListOf(),
         )
-        val payload = json.encodeToJsonElement(filter).toString()
 
+        // Always exclude EPUBs unless explicitly included
+        if (!preferences.getBoolean(SHOW_EPUB_PREF, SHOW_EPUB_DEFAULT)) {
+            filter.addStatement(
+                FilterComparison.NotContains,
+                FilterField.Formats,
+                "3",
```
Comment (majora2007) [inline src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt:315]: Avoid magic numbers/strings as much as possible. I would put the Formats as an enum.

File: src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt [hunk 6]
```diff
@@ -1569,10 +1577,22 @@ class Kavita(private val suffix: String = "") : ConfigurableSource, UnmeteredSou
...
                     ?: throw IOException("Invalid volume ID")
 
-                // Get all chapters & pages in this volume
+                // Get all pages in this volume
                 val volumeRequest = GET("$apiUrl/Volume/$volumeId", headersBuilder().build())
                 val volume = client.newCall(volumeRequest).execute().parseAs<VolumeDto>()
+                val matchingChapter = volume.chapters.firstOrNull() // or match a chapterId if available
+                    ?: throw IOException(helper.intl["error_no_chapters_found"])
+
                 val pages = mutableListOf<Page>()
```
Comment (majora2007) [inline src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt:1586]: [Nitpick] It might be more clear to rewrite this as:
```
val pages = (0 until matchingChapter.pages).map { i ->
    Page(
        index = i,
        imageUrl = "$apiUrl/Reader/image?chapterId=${matchingChapter.id}&page=$i&extractPdf=true&apiKey=$apiKey"
    )
}
```

Map is a very familiar method (ES6 with Javascript).

File: src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt [hunk 7]
```diff
@@ -1569,10 +1577,22 @@ class Kavita(private val suffix: String = "") : ConfigurableSource, UnmeteredSou
...
+                for (i in 0 until matchingChapter.pages) {
+                    pages.add(
+                        Page(
+                            index = i,
+                            imageUrl = "$apiUrl/Reader/image?chapterId=${matchingChapter.id}&page=$i&extractPdf=true&apiKey=$apiKey",
```
Comment (majora2007) [inline src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt:1591]: [Nitpick] Use lowercase for the api routes. The controller (Reader) should be lowercase.

**Review by majora2007 — APPROVED** [review]

File: src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt [hunk 8]
```diff
@@ -382,6 +384,39 @@ class Kavita(private val suffix: String = "") : ConfigurableSource, UnmeteredSou
             statements = mutableListOf(),
         )
 
+        // Handle text query first
+        if (query.isNotBlank()) {
```
Comment (majora2007) [inline src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt:388]: For the future, you might want to wrap these into methods that either return something or null or just do the modification. This will keep the code easier to understand.
